# Generated by Django 4.1.1 on 2022-10-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('alternate_phonenumber', models.CharField(blank=True, max_length=15)),
                ('addressline_one', models.CharField(max_length=100)),
                ('addressline_two', models.CharField(blank=True, max_length=100)),
                ('countryor_city', models.CharField(max_length=100)),
                ('postalcode', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('company_type', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'register',
            },
        ),
        migrations.CreateModel(
            name='Company_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=100)),
                ('company_type', models.CharField(max_length=100)),
                ('addressline_one', models.CharField(max_length=100)),
                ('addressline_two', models.CharField(max_length=100)),
                ('countryor_city', models.CharField(max_length=100)),
                ('postalcode', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='connection_details_keypairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=100)),
                ('connection_detail', models.CharField(max_length=100)),
                ('conn_pd_id', models.IntegerField()),
                ('key_pram', models.CharField(max_length=200, null=True)),
                ('value_pram', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('last_modified_by', models.CharField(max_length=100, null=True)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'connection_details',
            },
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='post_images')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'connections',
            },
        ),
        migrations.CreateModel(
            name='db_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'db_config',
            },
        ),
        migrations.CreateModel(
            name='db_sql_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=200)),
                ('sequelize_query', models.CharField(max_length=2000)),
                ('sql_validation', models.CharField(max_length=200)),
                ('sql_status', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'db_sql_extract',
            },
        ),
        migrations.CreateModel(
            name='Pipeline_details',
            fields=[
                ('Pipeline_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('Pipeline_detail_name', models.CharField(max_length=100)),
                ('pipeline_dtls_desc', models.CharField(max_length=100)),
                ('Pipeline_id', models.IntegerField()),
                ('db_SQL_id', models.IntegerField()),
                ('SQL_extract_name', models.CharField(max_length=100)),
                ('Target_table_name', models.CharField(max_length=100)),
                ('Source_table_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('Pipeline_dtls_status', models.DateField()),
                ('last_modified_by', models.CharField(max_length=100)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('Pipeline_dtls_truncate_load', models.CharField(max_length=100)),
                ('Pipeline_dtls_bench_mark_commit', models.CharField(max_length=100)),
                ('pipeline_dtls_parallel_load_allowed', models.CharField(max_length=100)),
                ('Pipeline_dtls_parallel_thread_count', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pipeline_details',
            },
        ),
        migrations.CreateModel(
            name='pipiline_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_schedule_desc', models.CharField(max_length=100)),
                ('Pipeline_schedule_name', models.CharField(max_length=100)),
                ('pipeline_detail_id', models.IntegerField()),
                ('pipeline_schedule_start_date', models.DateField()),
                ('pipeline_schedule_end_date', models.DateField()),
                ('pipeline_schedule_time', models.TimeField()),
                ('pipeline_schedule_run_imme', models.BooleanField()),
                ('pipeline_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pipline_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(blank=True, max_length=30)),
                ('Description', models.CharField(blank=True, max_length=30)),
                ('configuration_name', models.CharField(blank=True, max_length=30)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pipeline',
            },
        ),
        migrations.CreateModel(
            name='ScheduleDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_schedule_dependency_name', models.CharField(max_length=50)),
                ('parent_schedule_name', models.CharField(max_length=50)),
                ('child_schedule_name', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scheduledependency',
            },
        ),
    ]
