# Generated by Django 4.1.1 on 2022-11-02 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('alternate_phonenumber', models.CharField(blank=True, max_length=15)),
                ('addressline_one', models.CharField(max_length=100)),
                ('addressline_two', models.CharField(blank=True, max_length=100)),
                ('countryor_city', models.CharField(max_length=100)),
                ('postalcode', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('company_type', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'register',
            },
        ),
        migrations.CreateModel(
            name='Conn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('logo_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('key_param', models.JSONField()),
            ],
            options={
                'db_table': 'connections',
            },
        ),
        migrations.CreateModel(
            name='db_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'db_config',
            },
        ),
        migrations.CreateModel(
            name='db_sql_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=200)),
                ('sequelize_query', models.CharField(max_length=2000)),
                ('sql_validation', models.CharField(max_length=200)),
                ('sql_status', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'db_sql_extract',
            },
        ),
        migrations.CreateModel(
            name='pipiline_sch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_schedule_desc', models.CharField(max_length=100)),
                ('pipeline_schedule_name', models.CharField(max_length=100)),
                ('pipeline_detail_name', models.CharField(max_length=100)),
                ('pipeline_schedule_start_date', models.DateField()),
                ('pipeline_schedule_end_date', models.DateField()),
                ('pipeline_schedule_time', models.TimeField()),
                ('pipeline_schedule_run_imme', models.BooleanField()),
                ('pipeline_status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pipeline_sch',
            },
        ),
        migrations.CreateModel(
            name='pipline_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_detail_name', models.CharField(max_length=100)),
                ('pipeline_dtls_desc', models.CharField(max_length=100, null=True)),
                ('source_table_name', models.CharField(max_length=100)),
                ('target_table_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('last_modified_by', models.CharField(max_length=100, null=True)),
                ('last_modified_on', models.DateField(auto_now=True, null=True)),
                ('created_on', models.DateField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('pipeline_dtls_truncate_load', models.CharField(max_length=100, null=True)),
                ('pipeline_dtls_bench_mark_commit', models.CharField(max_length=100, null=True)),
                ('pipeline_dtls_parallel_load_allowed', models.CharField(max_length=100, null=True)),
                ('pipeline_dtls_parallel_thread_count', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'pipline_det',
            },
        ),
        migrations.CreateModel(
            name='pipline_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(blank=True, max_length=30)),
                ('Description', models.CharField(blank=True, max_length=30)),
                ('configuration_name', models.CharField(blank=True, max_length=30)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pipeline',
            },
        ),
        migrations.CreateModel(
            name='role_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('role_desc', models.CharField(max_length=100)),
                ('role_start_date', models.DateField()),
                ('role_end_date', models.DateField()),
                ('role_status', models.BooleanField()),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='role_detail_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('role_detail_name', models.CharField(max_length=100)),
                ('role_description', models.CharField(max_length=150)),
                ('role_handling_pages', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_schedule_dependency_name', models.CharField(max_length=50)),
                ('parent_schedule_name', models.CharField(max_length=50)),
                ('child_schedule_name', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scheduledependency',
            },
        ),
        migrations.CreateModel(
            name='con_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=100)),
                ('connection_detail', models.CharField(max_length=100)),
                ('key_pram', models.CharField(max_length=200, null=True)),
                ('value_pram', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('last_modified_by', models.CharField(max_length=100, null=True)),
                ('last_modified_on', models.DateField(auto_now=True, null=True)),
                ('created_on', models.DateField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('conn_pd_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conn_pd_id', to='datahub_v3_app.conn')),
                ('connection_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_id', to='datahub_v3_app.conn')),
            ],
            options={
                'db_table': 'con_details',
            },
        ),
    ]
