# Generated by Django 4.1.1 on 2022-11-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role_detail_api',
            table='role_detail',
        ),
    ]
