# Generated by Django 4.1.1 on 2022-11-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sche_id', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('status', models.CharField(max_length=40)),
            ],
        ),
    ]
