# Generated by Django 4.1.1 on 2022-10-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dumy_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=100)),
                ('connection_detail', models.CharField(max_length=100)),
                ('conn_pd_id', models.IntegerField(null=True)),
                ('key_pram', models.CharField(max_length=200, null=True)),
                ('value_pram', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('last_modified_by', models.CharField(max_length=100, null=True)),
                ('last_modified_on', models.DateField(auto_now=True, null=True)),
                ('created_on', models.DateField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'con_det',
            },
        ),
        migrations.DeleteModel(
            name='Company_Register',
        ),
        migrations.DeleteModel(
            name='connection_details_keypairs',
        ),
    ]
