# Generated by Django 4.1.1 on 2022-11-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0003_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_role_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300)),
                ('role_name', models.JSONField()),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users_role',
            },
        ),
        migrations.DeleteModel(
            name='users_role_view',
        ),
    ]
