# Generated by Django 4.1.1 on 2022-10-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0003_pipiline_sche_delete_pipiline_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipiline_sche',
            old_name='Pipeline_schedule_name',
            new_name='pipeline_schedule_name',
        ),
    ]
