# Generated by Django 4.1.1 on 2022-11-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0003_pipline_details_delete_pipline_det'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('source_connection_name', models.CharField(max_length=100)),
                ('target_connection_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'db_conf',
            },
        ),
        migrations.DeleteModel(
            name='db_config',
        ),
    ]
