# Generated by Django 4.1.1 on 2022-10-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0004_rename_pipeline_schedule_name_pipiline_sche_pipeline_schedule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connections',
            name='image',
        ),
        migrations.AddField(
            model_name='connections',
            name='conn_param',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connections',
            name='logo_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='connections',
            table=None,
        ),
    ]
