# Generated by Django 4.1.1 on 2022-11-04 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0004_db_conf_delete_db_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='con_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_detail', models.CharField(max_length=100)),
                ('con_str', models.JSONField()),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('last_modified_by', models.CharField(max_length=100, null=True)),
                ('last_modified_on', models.DateField(auto_now=True, null=True)),
                ('created_on', models.DateField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connection_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_id', to='datahub_v3_app.conn')),
            ],
            options={
                'db_table': 'con_detail',
            },
        ),
        migrations.DeleteModel(
            name='con_details',
        ),
    ]
