# Generated by Django 4.1.1 on 2022-10-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0005_remove_connections_image_connections_conn_param_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connections',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
