# Generated by Django 4.1.1 on 2022-11-15 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0005_role_details_api_delete_role_detail_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='pipline_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('Description', models.CharField(blank=True, max_length=30)),
                ('configuration_name', models.CharField(blank=True, max_length=30)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pipeline_api',
            },
        ),
        migrations.AlterField(
            model_name='role_api',
            name='role_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pipline_details',
            name='pipeline_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_id', to='datahub_v3_app.pipline_api'),
        ),
        migrations.DeleteModel(
            name='pipline_table',
        ),
    ]
