# Generated by Django 4.1.1 on 2022-10-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0006_alter_connections_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pipline_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(max_length=100)),
                ('pipeline_detail_name', models.CharField(max_length=100)),
                ('pipeline_dtls_desc', models.CharField(max_length=100)),
                ('pipeline_id', models.IntegerField()),
                ('db_sql_id', models.IntegerField()),
                ('sql_extract_name', models.CharField(max_length=100)),
                ('target_table_name', models.CharField(max_length=100)),
                ('source_table_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('pipeline_dtls_status', models.DateField()),
                ('last_modified_by', models.CharField(max_length=100)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('pipeline_dtls_truncate_load', models.CharField(max_length=100)),
                ('pipeline_dtls_bench_mark_commit', models.CharField(max_length=100)),
                ('pipeline_dtls_parallel_load_allowed', models.CharField(max_length=100)),
                ('pipeline_dtls_parallel_thread_count', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pipline_det',
            },
        ),
        migrations.DeleteModel(
            name='Pipeline_details',
        ),
        migrations.AlterModelTable(
            name='connections',
            table='conn',
        ),
    ]
