# Generated by Django 4.1.1 on 2022-11-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0006_users_role_view'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conn',
            table='conn',
        ),
    ]
