# Generated by Django 4.1.1 on 2022-10-19 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0008_pipiline_sch_delete_pipiline_sche'),
    ]

    operations = [
        migrations.CreateModel(
            name='con_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=100)),
                ('connection_detail', models.CharField(max_length=100)),
                ('key_pram', models.CharField(max_length=200, null=True)),
                ('value_pram', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('last_modified_by', models.CharField(max_length=100, null=True)),
                ('last_modified_on', models.DateField(auto_now=True, null=True)),
                ('created_on', models.DateField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('conn_pd_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conn_pd_id', to='datahub_v3_app.connections')),
                ('connection_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_id', to='datahub_v3_app.connections')),
            ],
            options={
                'db_table': 'con_details',
            },
        ),
        migrations.DeleteModel(
            name='dumy_model',
        ),
    ]
