# Generated by Django 4.1.1 on 2022-10-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0011_alter_user_managers_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='role_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('role_desc', models.CharField(max_length=100)),
                ('role_start_date', models.DateField()),
                ('role_end_date', models.DateField()),
                ('role_status', models.BooleanField()),
            ],
            options={
                'db_table': 'role',
            },
        ),
    ]
