# Generated by Django 4.1.1 on 2022-10-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0013_pipline_details_delete_pipline_det'),
    ]

    operations = [
        migrations.CreateModel(
            name='pipline_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_detail_name', models.CharField(max_length=100)),
                ('pipeline_dtls_desc', models.CharField(max_length=100, null=True)),
                ('source_table_name', models.CharField(max_length=100)),
                ('target_table_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('last_modified_by', models.CharField(max_length=100, null=True)),
                ('last_modified_on', models.DateField(auto_now=True, null=True)),
                ('created_on', models.DateField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('pipeline_dtls_truncate_load', models.CharField(max_length=100, null=True)),
                ('pipeline_dtls_bench_mark_commit', models.CharField(max_length=100, null=True)),
                ('pipeline_dtls_parallel_load_allowed', models.CharField(max_length=100, null=True)),
                ('pipeline_dtls_parallel_thread_count', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'pipline_det',
            },
        ),
    ]
