# Generated by Django 4.1.1 on 2022-10-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0014_pipline_det'),
        ('pipeline_framework', '0002_alter_pipe_fram_pipe_det_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pipline_details',
        ),
    ]
