# Generated by Django 4.1.1 on 2022-10-28 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0015_delete_pipline_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('logo_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('key_param', models.JSONField()),
            ],
            options={
                'db_table': 'connections',
            },
        ),
        migrations.AlterField(
            model_name='con_details',
            name='conn_pd_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conn_pd_id', to='datahub_v3_app.conn'),
        ),
        migrations.AlterField(
            model_name='con_details',
            name='connection_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_id', to='datahub_v3_app.conn'),
        ),
        migrations.DeleteModel(
            name='Connections',
        ),
    ]
