# Generated by Django 4.1.1 on 2022-10-27 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datahub_v3_app', '0013_pipline_details_delete_pipline_det'),
    ]

    operations = [
        migrations.CreateModel(
            name='pipe_fram',
            fields=[
                ('pipe_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pipe_id', serialize=False, to='datahub_v3_app.pipiline_sch', unique=True)),
                ('pipe_det_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipe_det_id', to='datahub_v3_app.pipline_details', unique=True)),
            ],
            options={
                'db_table': 'pipeline_frame',
            },
        ),
    ]
