# Generated by Django 4.1.1 on 2022-10-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub_v3_app', '0014_pipline_det'),
        ('pipeline_framework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipe_fram',
            name='pipe_det_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipe_det_id', to='datahub_v3_app.pipline_det', unique=True),
        ),
    ]
